### PR TITLE
Fix typos and refactor functions in messaging views

### PR DESCRIPTION
**Pull request by zxenonx**
I fixed some issues in messaging.py

- Update docstring, swagger docs and comments
- Remove unused imports
- I left two FIXME tag in the code. These parts need to be refactored.
- Let's please kindly review get() and delete() functions in MessageDetailsView.

Minor changes
- Update urls.py
- Fix typos in CONTRIBUTION.md
- Changes in Pipfile

### CODE REVIEW

**Comment by zxenonx** [comment]
@mykie88 @o4codes @man-of-mind @mukhtarB

**Review by man-of-mind — APPROVED** [review]
Nice boss, who is going to do the fix me?

I will personally assign it to you. @man-of-mind

**Review by mykie88 — APPROVED** [review]
Good job chief.

**Comment by zxenonx** [comment]
> Nice boss, who is going to do the fix me?

I will personally assign it to you @man-of-mind

**Comment by zxenonx** [comment]
> Good job chief.

😒 @mykie88

**Comment by man-of-mind** [comment]
> > Nice boss, who is going to do the fix me?
> 
> I will personally assign it to you @man-of-mind 

I will see to that boss.

**Pull request merged**
