### PR TITLE
Refactoring of Edit Message Endpoint and creation of Single Message Endpoint

### PR DESCRIPTION
**Pull request by blacdev**

### CODE REVIEW

**Review by o4codes — COMMENTED** [review]
Any difference between get message and single message endpoint ??

**Review by o4codes — COMMENTED** [review]
Can the put, get, delete of a message be under a single function or even a class or better still a viewset

**Review by o4codes — CHANGES_REQUESTED** [review]
Please can the name of your class be MessageDetailsView

Anything that doesn't streamline it to only EditMessage since it does more than edit message

**Review by o4codes — APPROVED** [review]

**Comment by blacdev** [comment]
The name has been changed

**Review by o4codes — APPROVED** [review]
Nice work
This is alright to be merged in my opinion

**Pull request merged**
